In [1]:
#https://enlight.nyc/projects/neural-network/

In [3]:
#simple feedforward neural network
'''
Takes inputs as a matrix (2D array of numbers)
Multiplies the input by a set weights (performs a dot product aka matrix multiplication)
Applies an activation function
Returns an output
Error is calculated by taking the difference from the desired output from the data and the predicted output. This creates our gradient descent, which we can use to alter the weights
The weights are then altered slightly according to the error.
To train, this process is repeated 1,000+ times. The more the data is trained upon, the more accurate our outputs will be.
'''

'\nTakes inputs as a matrix (2D array of numbers)\nMultiplies the input by a set weights (performs a dot product aka matrix multiplication)\nApplies an activation function\nReturns an output\nError is calculated by taking the difference from the desired output from the data and the predicted output. This creates our gradient descent, which we can use to alter the weights\nThe weights are then altered slightly according to the error.\nTo train, this process is repeated 1,000+ times. The more the data is trained upon, the more accurate our outputs will be.\n'

In [4]:
import numpy as np

In [21]:
# X = (hours studying, hours sleeping), y = score on test
xAll = np.array(([2, 9], [1, 5], [3, 6], [5, 10]), dtype=float) # input data
y = np.array(([92], [86], [89]), dtype=float) # output

# scale units between 0-1
xAll = xAll/np.amax(xAll, axis=0) # scaling input data
y = y/100 # scaling output data (max test score is 100)

# split data
X = np.split(xAll, [3])[0] # training data
xPredicted = np.split(xAll, [3])[1] # testing data

print(xAll,'\n'*2, y ,'\n'*2, X ,'\n'*2, xPredicted)

[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]
 [1.  1. ]] 

 [[0.92]
 [0.86]
 [0.89]] 

 [[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]] 

 [[1. 1.]]


In [46]:
class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
        #weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix from hidden to output layer
        
    def sigmoid(self, s):
        #activation function
        return 1/(1+np.exp(-s))
    
    def forward(self, X):
        #forward propagation
        self.z = np.dot(X, self.W1) # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z) # activation function
        self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3) # final activation function
        return o
   
    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)
    
    def backward(self, X, y, o):
        # backward propagate through the network
        self.o_error = y - o # error in output
        self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error

        self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights
        
    def train (self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)
        
    def saveWeights(self):
        np.savetxt("w1.txt", self.W1, fmt="%s")
        np.savetxt("w2.txt", self.W2, fmt="%s")

    def predict(self):
        print ("Predicted data based on trained weights: ")
        print ("Input (scaled): \n" + str(xPredicted))
        print ("Output: \n" + str(self.forward(xPredicted)))

In [54]:
NN = Neural_Network()

for i in range(1000): # trains the NN 1,000 times
  NN.train(X,y)

print ("Input: \n" + str(X))
print ("Actual Output: \n" + str(y))
print ("Predicted Output: \n" + str(NN.forward(X)))
print ("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) # mean sum squared loss

Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89545415]
 [0.87993262]
 [0.89452136]]
Loss: 
0.0003400835687652715


In [55]:
NN.saveWeights()
NN.predict()

Predicted data based on trained weights: 
Input (scaled): 
[[1. 1.]]
Output: 
[[0.90997025]]
